apiVersion: v2
name: myapp
description: A Helm chart for the DevOps Case Study Application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: myapp-database
  version: 0.1.0
  repository: file://../database-chart